name: CI Pipeline

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # This step checks out the repository's code

    - name: Read file using cat
      run: mv Demo.html home.html  # Replace with the actual path to the file you want to read
